service: MB-COVID-19-API

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: handler.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  environment:
    IS_LAMBDA: true

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http: 
          method: ANY 
          path: /
          cors: true
      - http: 
          method: ANY
          path: '{proxy+}'
          cors: true

package:
  exclude:
  - "__pycache__/**"
  - ".vscode/**"
  - ".github/**"
  - ".git/**"
  - "venv/**"
  - "tests/**"
  - ".gitignore"
  - LICENSE
  - README.md
  - requirements.txt
  